#+TITLE: Analysis of multivariate binomial data: case control or ascertainment sampling 
#+AUTHOR: Klaus Holst & Thomas Scheike
#+INCLUDE: header.org
----- 


* Overview 

When looking at multivariate binomial data with the aim of learning about the 
dependence that is present, possibly after correcting for some covariates many
models are available. 

   -  Random-effects models logistic regression covered elsewhere (glmer in lme4).

in the mets package you can fit the 

   -  Pairwise odds ratio model
   -  Bivariate Probit model 
      - With random effects
      - Special functionality for polygenic random effects modelling 
        such as ACE, ADE ,AE and so forth.
   -  Additive gamma random effects model 
      - Special functionality for polygenic random effects modelling 
        such as ACE, ADE ,AE and so forth.

These last three models are all fitted in the mets package using composite 
likelihoods for pairs of data.  The models can be fitted specifically based 
on specifying which pairs one wants to use for the composite score. 

The models are described in futher details in the binomial-twin vignette. 

** Case-Control Sampling 

Sometimes, pairs are recruited after a case-proband is selected. This 
proband, can be either  a 

 - case: must be representative of cases

or  a 

 - control: must be representative of controls

First thinking about pairs, we estimate parameters using the conditional 
likelihood given sampling wich for a binary 2 x 2 table can be 
written as
\[
\frac{P(i,j)}{P(j)}
\]
the probailty of seeing \( (i,j) \) for the pair, given that the proband was
observed as \( (j) \).


We note that if the marginal is known, or possibly estimated from the full 
cohort. Then we can estimate dependence paramters using just the terms
\( P(i,j) \) for the pairs. We can thus ignore the special sampling for
models with marginal specification.  If the marginal can not be obtained 
from other sources we need to maximize the full-pairwise-likelihood in all
paramters, that is both dependence and marginal parameters. 

Similary, one can select a whole family based on having selected a proband, that is 
selected a representative member of  either cases or controls.  In this case we 
fit the models by using composited likelihoods, considering all
pairs that involves the probands.  This will give some lacking efficiency 
compared to looking at the full likelihood of the family given the proband. 


** Ascertainment Sampling 

Similarly, in the setting of pairs we can select all pairs where there is at 
least one event of interest.  

First thinking about pairs, we estimate parameters using the conditional 
likelihood given sampling wich for a binary 2 x 2 table can be 
written as
\[
\frac{P(i,j)}{1-P(0,0)}
\]
the probailty of seeing \( (i,j) \) for the pair, given that it is sampled. 

If the marginal can estimated from a full sample we can then estimate the
dependence paramter using the ascertainment likelihood.

Generally, when whole families are ascertained the computation of the
true truncation probability can be hard to the fact that families are
hard to define in the real world. Nevertheless, if a random sample of such
family is at hand. We suggest to in these families take out all pairs that 
satisfies the ascertainment criterion. With a family, with given size \( n \)
we have binary observations \( (Y_1,...,Y_n) \). The family is sampled or  a
random sample of families such that
\[ 
\sum_{i=1}^n Y_i \geq 1.
\]
We let the conditional distribution given sampling, be denoted as 
\[ 
P^O(\cdot) = P(\cdot | \sum_{i=1}^n Y_i \geq 1) 
\]

Now, we note that all pairs within these family that satisfies that 
\( Y_i+Y_j \geq 1 \), will have distribution
\begin{align*}
P^O(Y_i=o_1, Y_j=o_2 | Y_i+Y_j \geq 1)  & = \frac{P^O(o_1,o_2)}{P^O( Y_i+Y_j \geq 1)} \\
                                        & = \frac{P(Y_i=o_1,Y_j=o_2, \sum_{i=1}^n Y_i \geq 1)}{ P( Y_i+Y_j \geq 1, \sum_{i=1}^n Y_i \geq 1)} \\
                                        & = \frac{P(Y_i=o_1,Y_j=o_2) }{ P( Y_i+Y_j \geq 1)} = \frac{P(o_1,o_2)}{1 - P(0,0)} 
\end{align*}
since we only consider the probabilities where \( o_1+o_2 \geq 1 \). 
Also here we could condition on covariates. 

So considering these pairs, or a random sample of them should yield valid 
inference. When standard errors are computed we need to rely on GEE type 
arguments. An advantage of this is that the ascertainment probability is much 
easier to get for the pairs. Again using the pairwise structure will   lead
to loss of efficiency compared to using the full likelihood of the ascertained
families. 



* The twin-stutter data

We consider the twin-stutter where for pairs of twins that are 
either dizygotic or monozygotic we have recorded whether the twins
are stuttering \cite{twinstut-ref}

We here consider MZ and same sex DZ twins. 

Looking at the data 

#+BEGIN_SRC R :results output :exports both :session *R* :cache yes 
library(mets)
data(twinstut)
twinstut$binstut <- 1*(twinstut$stutter=="yes")
twinstut <- subset(twinstut,zyg%in%c("mz","dz"))
head(twinstut)
#+END_SRC

#+RESULTS[460986aef71a4f8d43e07e2c3f2eeb6b8fafc0ae]:
#+begin_example
Loading required package: timereg
Loading required package: survival
Loading required package: lava
lava version 1.5.1
mets version 1.2.1.2

Attaching package: ‘mets’

The following object is masked _by_ ‘.GlobalEnv’:

    object.defined

Warning message:
failed to assign RegisteredNativeSymbol for cor to cor since cor is already defined in the ‘mets’ namespace
   tvparnr zyg stutter    sex age nr binstut
1  2001005  mz      no female  71  1       0
2  2001005  mz      no female  71  2       0
3  2001006  dz      no female  71  1       0
8  2001012  mz      no female  71  1       0
9  2001012  mz      no female  71  2       0
11 2001015  dz      no   male  71  1       0
#+end_example


- First,  we select an ascertaiment sample of the data, thus selecting
  a random sample of all ascertained pairs. 

- Secondly, we select a case-control sample of this data to illustrate the use
  of the methods.


* Ascertaiment Sampling 

Selecting the ascertained pairs 

#+BEGIN_SRC R :results output :exports both :session *R* :cache yes 
library(mets)
data(twinstut)
twinstut$binstut <- 1*(twinstut$stutter=="yes")
twinstut <- subset(twinstut,zyg%in%c("mz","dz"))
dnumeric(twinstut) <- ~.
dfactor(twinstut,labels=c("DZ","MZ")) <- binzyg~zyg.n
ddrop(twinstut) <- ~"*.n"

twinstut  <-   dby(twinstut,binstut~tvparnr,stuttot=sum,nn=seq_along,n=length)
twina     <-   subset(twinstut,n==2 & stuttot>=1)
#+END_SRC  

#+RESULTS[283e616501f0835eb3d97858e099321661ff2e30]:


Selecting on the pairs where there is stuttering at taking a look at the 
tables of discordance and concordance for the twins. 


#+BEGIN_SRC R :results output :exports both :session *R* :cache yes 
twinda <- fast.reshape(twina,id="tvparnr")
twind <- fast.reshape(twinstut,id="tvparnr")
dtable(twind,"binst*"~I(stuttot1>=1))
dtable(twinda,~"binst*")
#+END_SRC  

#+RESULTS[fdc6bdd7d0a1714bf6a5ab78c21402cfd94d4c71]:
#+begin_example
I(stuttot1 >= 1): FALSE

         binstut2    0
binstut1              
0                 6632
------------------------------------------------------------ 
I(stuttot1 >= 1): TRUE

         binstut2   0   1
binstut1                 
0                   0 289
1                 281 111

         binstut2   0   1
binstut1                 
0                   0 289
1                 281 111
#+end_example


Now doing the analyses 

** Biprobit model 

Looking at the full data for comparison. We estimate an unstructured
probit model with different correlations for MZ and DZ twins. 

#+BEGIN_SRC R :results output :exports both :session *R* :cache yes 
b1 <- biprobit(binstut~sex,~-1+binzyg,data=twinstut,id="tvparnr")
summary(b1)
#+END_SRC  

#+RESULTS[bea6e1be22170e51a234141d1e0dec930b050ac2]:
#+begin_example

              Estimate    Std.Err          Z p-value
(Intercept)  -1.794821   0.023289 -77.066826  0.0000
sexmale       0.401430   0.030179  13.301756  0.0000
r:binzygDZ    0.132458   0.062516   2.118802  0.0341
r:binzygMZ    1.096915   0.073574  14.909085  0.0000

logLik: -4400.536  mean(score^2): 1.022e-06 
    n pairs 
21288  7313 

Contrast:
	Dependence    [binzygDZ] 
	Mean          [(Intercept)] 

                        Estimate 2.5%    97.5%  
Rel.Recur.Risk          1.77662  0.92746 2.62577
OR                      1.88752  1.09432 3.25566
Tetrachoric correlation 0.13169  0.00993 0.24960
                                                
Concordance             0.00235  0.00140 0.00393
Casewise Concordance    0.06456  0.03937 0.10413
Marginal                0.03634  0.03287 0.04016
#+end_example




A similar analysis of the ascertained data reveals (some problems) ...

#+BEGIN_SRC R :results output :exports both :session *R* :cache yes 
ba1 <- biprobit(binstut~sex,~-1+binzyg,data=twina,id="tvparnr",pair.ascertained=TRUE)
summary(ba1)
#+END_SRC  

#+RESULTS[9c3652bd08fd976f96268483c24fedb479271f54]:
#+begin_example

              Estimate    Std.Err          Z p-value
(Intercept)   0.101193   0.031912   3.170993  0.0015
sexmale       0.049255   0.042886   1.148495  0.2508
r:binzygDZ   -3.952376   0.282620 -13.984759  0.0000
r:binzygMZ   -0.840831   0.169676  -4.955514  0.0000

logLik: -690.9136  mean(score^2): 5.008e-11 
    n pairs 
 1362   681 

Contrast:
	Dependence    [binzygDZ] 
	Mean          [(Intercept)] 

                        Estimate 2.5%     97.5%   
Rel.Recur.Risk           0.27611  0.13140  0.42081
OR                       0.00000      NaN      NaN
Tetrachoric correlation -0.99926 -0.99976 -0.99777
                                                  
Concordance              0.08060  0.04294  0.14627
Casewise Concordance     0.14918  0.08234  0.25520
Marginal                 0.54030  0.51540  0.56501
#+end_example


** Odd-Ratio modelling 

   First looking at the marginal model based on the full data we find the 
   overall level of stuttering and also that males have a much higher 
   stuttering risk.

#+BEGIN_SRC R :results output :exports both :session *R* :cache yes 
margbin <- glm(binstut~factor(sex),data=twinstut,family=binomial())
summary(margbin)
#+END_SRC  

#+RESULTS[43c119c7bb198ea53d0767c4092b2e9806c6448b]:
#+begin_example

Call:
glm(formula = binstut ~ factor(sex), family = binomial(), data = twinstut)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-0.4127  -0.4127  -0.2716  -0.2716   2.5763  

Coefficients:
                Estimate Std. Error z value Pr(>|z|)    
(Intercept)     -3.28191    0.05000  -65.64   <2e-16 ***
factor(sex)male  0.86171    0.06211   13.87   <2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 9328.6  on 21287  degrees of freedom
Residual deviance: 9124.7  on 21286  degrees of freedom
AIC: 9128.7

Number of Fisher Scoring iterations: 6
#+end_example


First, fitting the OR model for MZ and DZ for the full data, we find 
that MZ have a much higher dependence than DZ twins. 


#+BEGIN_SRC R :results output :exports both :session *R* :cache yes 
theta.des <- model.matrix( ~-1+factor(zyg),data=twinstut)
bin <- binomial.twostage(margbin,data=twinstut,var.link=1,
                          clusters=twinstut$tvparnr,theta.des=theta.des)
summary(bin)
#+END_SRC  

#+RESULTS[8c26ce701761f89ffb95486a513cd5f5e6997251]:
#+begin_example
Dependence parameter for Odds-Ratio (Plackett) model 
With log-link 
$estimates
                  theta        se
factor(zyg)dz 0.5238541 0.2400861
factor(zyg)mz 3.4930902 0.1865567

$or
              Estimate Std.Err   2.5% 97.5%  P-value
factor(zyg)dz     1.69   0.405  0.894  2.48 3.11e-05
factor(zyg)mz    32.89   6.135 20.862 44.91 8.31e-08

$type
[1] "plackett"

attr(,"class")
[1] "summary.mets.twostage"
#+end_example

Now, using the overall marginal we look at the adjusted likelihood and
find very similar results on the ascertained sample. Note, that the marginals 
are crucial for this analysis to give  useful results.


#+BEGIN_SRC R :results output :exports both :session *R* :cache yes 
theta.des <- model.matrix( ~-1+factor(zyg),data=twina)
bina <- binomial.twostage(margbin,data=twina,var.link=1,
             clusters=twina$tvparnr,theta.des=theta.des,
			 pair.ascertained=1)
summary(bina)
#+END_SRC  

#+RESULTS[09872d053ab60974d32ac4746b1318422ef5d50e]:
#+begin_example
Dependence parameter for Odds-Ratio (Plackett) model 
With log-link 
$estimates
                  theta        se
factor(zyg)dz 0.4874213 0.2472523
factor(zyg)mz 3.4753766 0.1985974

$or
              Estimate Std.Err   2.5% 97.5%  P-value
factor(zyg)dz     1.63   0.403  0.839  2.42 5.24e-05
factor(zyg)mz    32.31   6.417 19.734 44.89 4.77e-07

$type
[1] "plackett"

attr(,"class")
[1] "summary.mets.twostage"
#+end_example


** Additive gamma modelling 

   First, again for comparision fitting the full data for the AE model. We get 
   the size of the genetic variance in this model. 

#+BEGIN_SRC R :results output :exports both :session *R* :cache yes 
out <- twin.polygen.design(twinstut,id="tvparnr",zygname="zyg",zyg="dz",type="ae")
bintwin <- binomial.twostage(margbin,data=twinstut,
     clusters=twinstut$tvparnr,detail=0,theta=c(0.1)/1,var.link=0,
     random.design=out$des.rv,theta.des=out$pardes)
summary(bintwin)
#+END_SRC  

#+RESULTS[fedcb0c760bb61780b7308eb54c14c7156945e51]:
#+begin_example
Dependence parameter for Clayton-Oakes model
Variance of Gamma distributed random effects 
$estimates
                theta         se
dependence1 0.9094847 0.09536268

$type
[1] "clayton.oakes"

$h
            Estimate Std.Err 2.5% 97.5% P-value
dependence1        1       0    1     1       0

$vare
NULL

$vartot
   Estimate Std.Err  2.5% 97.5%  P-value
p1    0.909  0.0954 0.723   1.1 1.47e-21

attr(,"class")
[1] "summary.mets.twostage"
#+end_example


We first here take at the look at the marginal model for the ascertained 
sample, and note as expected that this sample give highly biased estimated for 
the
 marginal model. 



#+BEGIN_SRC R :results output :exports both :session *R* :cache yes 
outa <- twin.polygen.design(twina,id="tvparnr",zygname="zyg",zyg="dz",type="ae")
marga <- glm(binstut~sex,data=twina,family=binomial())
summary(marga)
#+END_SRC  

#+RESULTS[141ed981ded3d765143fdecd0e64abe3247268f8]:
#+begin_example

Call:
glm(formula = binstut ~ sex, family = binomial(), data = twina)

Deviance Residuals: 
   Min      1Q  Median      3Q     Max  
-1.334  -1.298   1.028   1.028   1.061  

Coefficients:
            Estimate Std. Error z value Pr(>|z|)   
(Intercept)  0.27895    0.08739   3.192  0.00141 **
sexmale      0.08242    0.11237   0.733  0.46328   
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 1851.8  on 1361  degrees of freedom
Residual deviance: 1851.2  on 1360  degrees of freedom
AIC: 1855.2

Number of Fisher Scoring iterations: 4
#+end_example


Now, using the overall marginal model we look at the adjusted likelihood and
find very similar results on the ascertained sample. Note, that the marginals 
are crucial for this analysis to give  useful results.

#+BEGIN_SRC R :results output :exports both :session *R* :cache yes 
abintwin1 <- binomial.twostage(margbin,data=twina,
               clusters=twina$tvparnr,detail=0,theta=c(0.1)/1,var.link=0,
               random.design=outa$des.rv,theta.des=outa$pardes,pair.ascertained=1)
summary(abintwin1)
#+END_SRC  

#+RESULTS[a75e336dbc2c0e29b853d3176999f82fe284c5ec]:
#+begin_example
Dependence parameter for Clayton-Oakes model
Variance of Gamma distributed random effects 
$estimates
                theta         se
dependence1 0.8920274 0.09732786

$type
[1] "clayton.oakes"

$h
            Estimate Std.Err 2.5% 97.5% P-value
dependence1        1       0    1     1       0

$vare
NULL

$vartot
   Estimate Std.Err  2.5% 97.5%  P-value
p1    0.892  0.0973 0.701  1.08 4.95e-20

attr(,"class")
[1] "summary.mets.twostage"
#+end_example


In fact for this model we can also do a full-MLE fitting jointly the 
dependence paramters and the marginal model. This is based on the
twostage option (twostage=0 is MLE). Here the starting value is given at
the marginal model for the ascertained model. This gives quite similar
results to the previous analyses with a genetic variance around 1. 


#+BEGIN_SRC R :results output :exports both :session *R* :cache yes 
aabintwin1 <- binomial.twostage(marga,data=twina,
                clusters=twina$tvparnr,detail=0,theta=c(0.1)/1,var.link=0,
                random.design=outa$des.rv,theta.des=outa$pardes,pair.ascertained=1,twostage=0)
summary(aabintwin1)
coef(marga)
coef(margbin)
#+END_SRC  

#+RESULTS[2ff58c09a7bf895d2e0fc51d09b74fcd3460c5e1]:
#+begin_example
Dependence parameter for Clayton-Oakes model
Variance of Gamma distributed random effects 
$estimates
               theta        se
dependence1 1.014398 0.1045593

$type
[1] "clayton.oakes"

$h
            Estimate Std.Err 2.5% 97.5% P-value
dependence1        1       0    1     1       0

$vare
NULL

$vartot
   Estimate Std.Err  2.5% 97.5%  P-value
p1     1.01   0.105 0.809  1.22 2.97e-22

$marginal
             Coef.      SE Robust SE     z P-val lower2.5% upper97.5%
dependence2 -4.350 0.08560   0.08560 -50.8     0    -4.520     -4.180
dependence3  0.551 0.00606   0.00606  90.8     0     0.539      0.563

attr(,"class")
[1] "summary.mets.twostage"
(Intercept)     sexmale 
  0.2789484   0.0824214
    (Intercept) factor(sex)male 
     -3.2819072       0.8617053
#+end_example


* Case Control Sampling 

  First, taking out all cases and one control for each case, we establish the
  pairs of these probands. This is based on keeping track of the twin related 
  to the proband. Here using some utility functions in the mets packages. 

  Then we write up the random design vectors  and the parameter design for 
  each pair using the kinship coefficient. 

  When specifying the pairs in the case-control setup the second column should
  be the probands. 


#+BEGIN_SRC R :results output :exports both :session *R* :cache yes 

twinstut  <-   dby(twinstut,binstut~tvparnr,stuttot=sum,nn=seq_along,n=length)
twinstut <-    subset(twinstut,n==2)
twinstut  <-   dtransform(twinstut,nnrow=1:nrow(twinstut))
twinstut  <-   dby(twinstut,binstut~tvparnr,nnn=seq_along)
twinstut  <-   dby2(twinstut,nnrow~tvparnr,pairnr=rev)

cases <- which(twinstut$binstut==1)
controls <- sample(which(twinstut$binstut==0),1217)
rowsca <- with(twinstut,nnrow[cases])
rowsco <- with(twinstut,nnrow[controls])
rpairs <- c(rowsca,rowsco)
cc.pairs <- cbind( with(twinstut,pairnr.nnrow[rpairs]),rpairs)

ids <- sort(unique(c(cc.pairs)))
###
pairsids <- c(cc.pairs)
pair.new <- matrix(fast.approx(ids,pairsids),ncol=2)
head(pair.new)

dataid <- dsort(twinstut[ids,],"tvparnr")
dataid=dtransform(dataid,kinship=0.5)
dataid=dtransform(dataid,kinship=1,binzyg=="MZ")
kinship <- dataid$kinship[pair.new[,2]]

out <- make.pairwise.design(pair.new,kinship,type="ae") 
names(out)
out$random.des[,,1]
out$theta.des[,,1]
#+END_SRC  

#+RESULTS[3651f85485d35a77ed42c7c7baefb656edfa0662]:
#+begin_example
     [,1] [,2]
[1,]   10    9
[2,]   18   17
[3,]   22   21
[4,]   40   39
[5,]   44   43
[6,]   58   57
[1] "random.design" "theta.des"     "ant.rvs"
     [,1] [,2] [,3]
[1,]    1    1    0
[2,]    1    0    1
[1] 0.5 0.5 0.5
#+end_example


Now doing the analyses, first with know marginals, that is marginals from the 
full data. For this analysis, since marginals do not contain dependence 
parameters we do not need to specify that this is case-control sampling. 
Having a correct is crucial for this to work, but this is certainly often 
possible in register based studies where a full cohort is also available. 

#+BEGIN_SRC R :results output :exports both :session *R* :cache yes 
cc  <- binomial.twostage(margbin,data=dataid,
			    clusters=dataid$tvparnr,
	         pairs=pair.new,
	         random.design=out$random.design,
             theta.des=out$theta.des,
	         pairs.rvs=out$ant.rvs,
             case.control=0,twostage=1)
summary(cc)
#+END_SRC  

#+RESULTS[71541277ed8066c4e68e3d0e00d12dd627335a87]:
#+begin_example
Dependence parameter for Clayton-Oakes model
Variance of Gamma distributed random effects 
$estimates
                theta         se
dependence1 0.8877835 0.09785569

$type
[1] "clayton.oakes"

$h
            Estimate Std.Err 2.5% 97.5% P-value
dependence1        1       0    1     1       0

$vare
NULL

$vartot
   Estimate Std.Err  2.5% 97.5%  P-value
p1    0.888  0.0979 0.696  1.08 1.16e-19

attr(,"class")
[1] "summary.mets.twostage"
#+end_example


We now do the same analysis specifying the case-control sampling. This 
should result in the same dependence parameters as is also the case.

#+BEGIN_SRC R :results output :exports both :session *R* :cache yes 
cc3 <- binomial.twostage(margbin,data=dataid,
			    clusters=dataid$tvparnr,
                 pairs=pair.new,
                 random.design=out$random.design,
                 theta.des=out$theta.des,
                 pairs.rvs=out$ant.rvs,
                 case.control=1,twostage=1)
summary(cc3)
#+END_SRC  

#+RESULTS[5a7c61318ba1b8697ef5d99d9fd98c0f53905858]:
#+begin_example
Dependence parameter for Clayton-Oakes model
Variance of Gamma distributed random effects 
$estimates
                theta         se
dependence1 0.8877835 0.09785569

$type
[1] "clayton.oakes"

$h
            Estimate Std.Err 2.5% 97.5% P-value
dependence1        1       0    1     1       0

$vare
NULL

$vartot
   Estimate Std.Err  2.5% 97.5%  P-value
p1    0.888  0.0979 0.696  1.08 1.16e-19

attr(,"class")
[1] "summary.mets.twostage"
#+end_example

This model can  also be fitted using a full likelhood of both dependence 
parameters and marginal parameters. Here there is no need to have a 
correctly specified marginal. We here use the marginal fitting from the
case-control data as as starting values.  Again we find a genetic variance 
around 1. The marginal parameters are also consistent with the results from 
the full analyses for the marginal parameters. 

#+BEGIN_SRC R :results output :exports both :session *R* :cache yes 
marga <- glm(binstut~sex,data=dataid,family=binomial())
cc3 <- binomial.twostage(marga,data=dataid,
             clusters=dataid$tvparnr,
             pairs=pair.new,
             random.design=out$random.design,
             theta.des=out$theta.des,
             pairs.rvs=out$ant.rvs,
             case.control=1,twostage=0)
summary(cc3)
#+END_SRC  

#+RESULTS[309850e156fcbca4ae3376cabd3bdf6a7113be20]:
#+begin_example
Dependence parameter for Clayton-Oakes model
Variance of Gamma distributed random effects 
$estimates
                theta         se
dependence1 0.9276133 0.09759565

$type
[1] "clayton.oakes"

$h
            Estimate Std.Err 2.5% 97.5% P-value
dependence1        1       0    1     1       0

$vare
NULL

$vartot
   Estimate Std.Err  2.5% 97.5%  P-value
p1    0.928  0.0976 0.736  1.12 2.01e-21

$marginal
             Coef.      SE Robust SE       z P-val lower2.5% upper97.5%
dependence2 -3.250 0.00149   0.00149 -2180.0     0     -3.25     -3.250
dependence3  0.182 0.01620   0.01620    11.3     0      0.15      0.214

attr(,"class")
[1] "summary.mets.twostage"
#+end_example


When probands are related, here we may choose both case and controls from
the same twin-pair then we need to adjust standard errors by grouping together
contribution from related probands. This can be done using the
se.cluster option that specifies how to cluster in the computation of the
standard errors. In this case, however, this will be same as the 
clusters since these also are identical across pairs.

* Combining Case Control and Ascertainment Sampling 

When specifying such models based on the pairs, it is in fact possible to
combine ascertained pairs with case-control sampling by specifing vectors
as the case.control=c(1,0,1,0) and pair.ascertained=c(0,1,0,1) arguments.  
Here with two case-control pairs, and two ascertained pairs. 

