* preample 							     :ignore:

  #+TITLE: Utility functions
  #+AUTHOR: Klaus K. Holst and Thomas Scheike
  #+email: k.k.holst@biostat.ku.dk
  #+LATEX_CLASS: tufte-handout
  #+LATEX_CLASS_OPTIONS: [a4paper]
  #+PROPERTY: header-args:R  :session *R* :cache no :width 550 :height 450
  #+PROPERTY: header-args  :eval never-export :exports both :results output :tangle yes :comments yes 
  #+PROPERTY: header-args:R+ :colnames yes :rownames no :hlines yes
  #+OPTIONS: timestamp:t title:t date:t author:t creator:nil toc:nil 
  #+OPTIONS: h:4 num:t tags:nil d:t ^:{}
  #+LATEX_HEADER: \lstset{language=R,keywords={},morekeywords={}}
  #+LATEX_HEADER: \usepackage{zlmtt}
  #+LATEX_HEADER: \setlength{\parindent}{0em}
  #+LATEX_HEADER: %%\setlength{\parindent}{default}
  #+LaTeX: \setlength{\parindent}{0em} %\setlength{\parindent}{default}

* Introduction

Data summaries

| =dhead=        | a |
| =dtail=        | a |
| =dsummary=     |   |
| =dprint,dlist= |   |
| =dlevels=      |   |
| =dunique=      |   |
| =dstr=         |   |


Data processing

| =dsort=             | a |
| =dreshape=          |   |
| =dcut=              |   |
| =drm=               |   |
| =dkeep=             |   |
| =dnames=, =drename=   |   |
| =ddrop=             |   |
| =dfactor=, =dnumeric= |   |
| =dsubset=           |   |
| =dlag=              |   |
| =drelevel=          |   |
| =dsample=           |   |


Aggregation
| =dby=                         |   |
| =daggregate=                  |   |
| =deval=                       |   |
| =deval2=                      |   |
| =dscalar=                     |   |
| =dmean=, =dsum=, =dsd=, =dquantile= |   |
| =dcor=                        |   |
| =dcount=                      |   |
| =dtable=                      |   |


#+BEGIN_SRC R
library(mets)
#+END_SRC

#+RESULTS:
#+begin_example
Loading required package: timereg
Loading required package: survival
Loading required package: lava
lava version 1.5
mets version 1.2.1.2

Attaching package: ‘mets’

The following object is masked _by_ ‘.GlobalEnv’:

    object.defined
#+end_example


* Data summary

We will use a subset of the TRACE data available in the =timereg= package, which consists of a random sub-sample of 300 patients
out of the full cohort consisting of approximately 6000 patients. It
contains data relating survival of patients after myocardial
infarction to various risk factors.

#+BEGIN_SRC R
data(sTRACE, package="timereg")
dhead(sTRACE)
#+END_SRC

#+RESULTS:
:         no wmi status chf    age sex diabetes     time vf
: X1944 1944 1.5      9   0 84.924   1        1 1.345000  0
: X5783 5783 1.9      0   1 74.193   0        0 6.910000  0
: X784   784 0.8      9   0 78.081   0        1 0.196000  0
: X3763 3763 1.3      0   0 55.479   1        0 7.543000  0
: X2927 2927 1.6      0   1 62.997   0        0 7.126000  0
: X4511 4511 1.0      9   1 67.644   1        0 4.532606  0

\cite{TRACE}



- no :: 
- wmi ::
- status :: 

Search
 
timereg
Flexible Regression Models for Survival Data
Search within the timereg package


Man pages 37
Functions 157
Home /  CRAN  /  timereg  /  TRACE: The TRACE study group of myocardial infarction
TRACE: The TRACE study group of myocardial infarction

Description Format Source Examples
Description

The TRACE data frame contains 1877 patients and is a subset of a data set consisting of approximately 6000 patients. It contains data relating survival of patients after myocardial infarction to various risk factors.

sTRACE is a subsample consisting of 300 patients.

tTRACE is a subsample consisting of 1000 patients.

Format

This data frame contains the following columns:

id
a numeric vector. Patient code.
status
a numeric vector code. Survival status. 9: dead from myocardial infarction, 0: alive, 7: dead from other causes.
time
a numeric vector. Survival time in years.
chf
a numeric vector code. Clinical heart pump failure, 1: present, 0: absent.
diabetes
a numeric vector code. Diabetes, 1: present, 0: absent.
vf
a numeric vector code. Ventricular fibrillation, 1: present, 0: absent.
wmi
a numeric vector. Measure of heart pumping effect based on ultrasound measurements where 2 is normal and 0 is worst.
sex
a numeric vector code. 1: female, 0: male.
age
a numeric vector code. Age of patient.
Source

The TRACE study group.


  #+BEGIN_mnote
  Here a margin note
  #+END_mnote

** a 

#+BEGIN_SRC R

n <- 20
m <- lava::lvm(letters)
d <- lava::sim(m,n)
 
dlist(d,~a+b+c | a>0)
dlist(d, a+b~c>0 | a>0)

#+END_SRC

#+RESULTS:
#+begin_example
    a       b         c      
2   0.46194  0.3921   -1.0336
3   0.04078 -1.0158   -0.5276
5   1.54748  2.2264    1.2505
6   1.14713  0.3490   -2.0616
8   0.50202 -1.0107   -0.3254
---                          
12  0.35184  0.229618  0.2654
13  0.75788  0.878370  0.5124
16  0.88593 -1.531461  0.8248
17  0.73966  0.191873  1.3537
18  0.05047  0.009801 -0.1950
c > 0: FALSE
   a       b        
2  0.46194  0.392068
3  0.04078 -1.015844
6  1.14713  0.349026
8  0.50202 -1.010701
9  0.41647  0.293009
18 0.05047  0.009801
------------------------------------------------------------ 
c > 0: TRUE
   a       b      
5  1.54748  2.2264
11 0.07824  1.3422
12 0.35184  0.2296
13 0.75788  0.8784
16 0.88593 -1.5315
17 0.73966  0.1919
#+end_example


#+BEGIN_SRC R
dmean('Petal' ~ Species, data=iris, regex=TRUE)
#+END_SRC

#+RESULTS:
:      Species Petal.Length Petal.Width
: 1     setosa        1.462       0.246
: 2 versicolor        4.260       1.326
: 3  virginica        5.552       2.026


  #+NAME: fig1
  #+BEGIN_SRC R :exports both :file figs/fig1.png :results output graphics
    plot(1)
    #+END_SRC

  #+ATTR_LaTeX: :width \textwidth :center t
  #+CAPTION: Important figure. label:fig1
  #+RESULTS: fig1

  \vspace*{1em}

  #+BEGIN_marginfigure
  #+ATTR_LATEX: :width 2cm :float nil :center t
  #+CAPTION: Important margin figure. label:fig2
  #+RESULTS: fig1

  #+END_marginfigure





  \cite{Tufte2006}
* Tables

#+BEGIN_SRC R
data(sTRACE, package="timereg")
dhead(sTRACE)
dcut(sTRACE) <-  wmicat~wmi
dtable(sTRACE, sex+diabetes+wmicat~vf | age<60)
dby(sTRACE, wmi ~ diabetes+sex, m=mean, q50=median, sd=sd, REDUCE=T)
dhead(sTRACE, 'wmi*' ~ sex)
#+END_SRC

#+RESULTS:
#+begin_example
        no wmi status chf    age sex diabetes     time vf
X1944 1944 1.5      9   0 84.924   1        1 1.345000  0
X5783 5783 1.9      0   1 74.193   0        0 6.910000  0
X784   784 0.8      9   0 78.081   0        1 0.196000  0
X3763 3763 1.3      0   0 55.479   1        0 7.543000  0
X2927 2927 1.6      0   1 62.997   0        0 7.126000  0
X4511 4511 1.0      9   1 67.644   1        0 4.532606  0
vf: 0

             wmicat [0.4,1.1] (1.1,1.4] (1.4,1.8] (1.8,2.7]
sex diabetes                                               
0   0                       4         2         3         5
    1                       0         2         1         1
1   0                      15        17        37        24
    1                       0         3         2         1
------------------------------------------------------------ 
vf: 1

             wmicat [0.4,1.1] (1.1,1.4] (1.4,1.8] (1.8,2.7]
sex diabetes                                               
0   0                       1         1         0         1
1   0                       1         2         2         0
  diabetes sex        m  q50        sd
1        0   0 1.437762 1.50 0.3810298
2        1   0 1.384211 1.30 0.4272173
3        0   1 1.434839 1.45 0.4017105
4        1   1 1.150000 1.15 0.4299009
sex: 0
      wmi    wmicat
X5783 1.9 (1.8,2.7]
X784  0.8 [0.4,1.1]
X2927 1.6 (1.4,1.8]
X1085 0.9 [0.4,1.1]
X5249 1.7 (1.4,1.8]
X6311 0.7 [0.4,1.1]
------------------------------------------------------------ 
sex: 1
      wmi    wmicat
X1944 1.5 (1.4,1.8]
X3763 1.3 (1.1,1.4]
X4511 1.0 [0.4,1.1]
X3122 1.9 (1.8,2.7]
X5441 1.4 (1.1,1.4]
X1280 1.1 [0.4,1.1]
#+end_example


#+BEGIN_SRC R
library("magrittr")
library("mets")

op <- par(mfrow=c(1,3))
l <- 
    iris %>% dsubset('*Length'~Species | Sepal.Width>mean(Sepal.Width)) %>%
    lapply(function(x,...) lm(Sepal.Length~Petal.Length,x)) %>%
    lapply(plotConf)
par(op)

dtable(iris, Species+dcut(Petal.Width,4)~1)
dtable(iris, Species+dcut(Petal.Width,4)~1|Sepal.Width>median(Sepal.Width))
dtable(iris, Species+dcut(Petal.Width,4)~
                 dcut(Petal.Length,breaks=2)|
                 Sepal.Width>mean(Sepal.Width))

#+END_SRC

#+RESULTS:
#+begin_example

           dcut(Petal.Width, 4) [0.1,0.3] (0.3,1.3] (1.3,1.8] (1.8,2.5]
Species                                                                
setosa                                 41         9         0         0
versicolor                              0        28        22         0
virginica                               0         0        16        34

           dcut(Petal.Width, 4) [0.1,0.2] (0.2,0.4] (0.4,1.8] (1.8,2.5]
Species                                                                
setosa                                 28        12         2         0
versicolor                              0         0         8         0
virginica                               0         0         2        15
dcut(Petal.Length, breaks = 2): [1,1.6]

           dcut(Petal.Width, 4) [0.1,0.2] (0.2,0.4] (0.4,1.8] (1.8,2.5]
Species                                                                
setosa                                 26         9         1         0
versicolor                              0         0         0         0
virginica                               0         0         0         0
------------------------------------------------------------ 
dcut(Petal.Length, breaks = 2): (1.6,6.7]

           dcut(Petal.Width, 4) [0.1,0.2] (0.2,0.4] (0.4,1.8] (1.8,2.5]
Species                                                                
setosa                                  2         3         1         0
versicolor                              0         0         8         0
virginica                               0         0         2        15
#+end_example

* dby
#+BEGIN_SRC R
library(magrittr)
sTRACE %>% dby2(chf+vf~1, mean, median) %>% dhead
#+END_SRC

#+RESULTS:
: Error in terms.formula(formula, data = data, specials = "regex") : 
:   object '.' not found

#+BEGIN_SRC R
library(magrittr)
sTRACE %>% dby(chf+vf, mean, median) 
#+END_SRC

#+BEGIN_SRC R



dby(iris, 'Length' ~ Species, mean, REGEX=T, COLUMN=T, REDUCE=T)
dby(iris, 'Length' ~ Species, mean, REGEX=T, COLUMN=T, REDUCE=T)
dby(iris, '*Length' ~ Species, mean, COLUMN=T, REDUCE=T)
dby(iris, '*Length' ~ Species, mean)
dby(iris, 'Length' ~ Species, mean, REGEX=T)
dby(iris, 'Length' ~ Species, mean, COLUMN=T, REGEX=T, REDUCE=T)
   
dby(iris, 'Length' ~ Species, mean, REGEX=T, REDUCE=1)
dby(iris, 'Length' ~ Species, mean, REGEX=T, REDUCE=1, COLUMN=T)
dby(iris, 'Length' ~ Species, mean, REGEX=T, REDUCE=1, COLUMN=T)

#+END_SRC

#+BEGIN_SRC R
lapply(list(median, mean), function(f) dscalar(sTRACE, chf+vf~sex, fun=f))
#+END_SRC


#+BEGIN_SRC R
dbyr(sTRACE, wmi ~ vf+sex|age>80, mean(x^2), mean(log(x)), mean, n=length)
#+END_SRC

#+RESULTS:
:   vf sex mean(x^2) mean(log(x))     mean   n
: 1  0   0  2.224133    0.3231019 1.440000 150
: 2  1   0  1.857500    0.2492690 1.325000  12
: 3  0   1  2.184361    0.3028986 1.420561 321
: 4  1   1  1.701176    0.1402013 1.235294  17


#+BEGIN_SRC R
dby(sTRACE, wmi+age ~ vf+sex, 
#+END_SRC
