// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef __mets_h__
#define __mets_h__

#include "mets_RcppExports.h"

#endif // __mets_h__
