# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ApplyBy <- function(idata, icluster, f) {
    .Call('mets_ApplyBy', PACKAGE = 'mets', idata, icluster, f)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('mets_RcppExport_registerCCallable', PACKAGE = 'mets')
})
