# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.loglikMVN <- function(Yl, yu, status, Mu, dmu, S, ds, z, su, dsu, threshold, dthreshold, Score) {
    .Call('mets_loglikMVN', PACKAGE = 'mets', Yl, yu, status, Mu, dmu, S, ds, z, su, dsu, threshold, dthreshold, Score)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('mets_RcppExport_registerCCallable', PACKAGE = 'mets')
})
